### ISSUE TITLE
Only 1 adapter is created after building the module

### ISSUE THREAD

**Issue by mario-mk** [bas-t/tbs-dvbloopback#2]
Dear Tycho
OS: Ubuntu 18.04.02 LTS
Kernel version: 4.10.17 (downgraded by purpose from 4.18, as this code is for kernel <=4.10)
physical dvb adapters available before compiling: 4
command executed: ./configure --adapters=8 --update=no --dvbc=no

After installation and reboot and after loading the module into kernel (modprobe dvbloopback) only 1 additional virtual adapter is created in /dev directory. I need more.
It was working with 4.4.0-59 and ubuntu 16.04.

I would appreciate feedback on this.
regards

**Comment by bas-t** [comment]
I'm  not maintaining this software anymore..
